// Mocks generated by Mockito 5.4.2 from annotations
// in homebase_flutter_weather_app/test/features/weather/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:homebase_flutter_weather_app/core/network/network_info.dart'
    as _i7;
import 'package:homebase_flutter_weather_app/features/weather/data/data_sources/weather_local_data_source.dart'
    as _i6;
import 'package:homebase_flutter_weather_app/features/weather/data/data_sources/weather_remote_data_source.dart'
    as _i3;
import 'package:homebase_flutter_weather_app/features/weather/data/models/weather_model.dart'
    as _i2;
import 'package:homebase_flutter_weather_app/features/weather/data/models/weather_search_item_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSourceInterface extends _i1.Mock
    implements _i3.WeatherRemoteDataSourceInterface {
  @override
  _i4.Future<_i2.WeatherModel> getWeatherDetailInfoByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherDetailInfoByName,
          [name],
        ),
        returnValue: _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getWeatherDetailInfoByName,
            [name],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getWeatherDetailInfoByName,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.WeatherModel>);

  @override
  _i4.Future<List<_i5.WeatherSearchItemModel>> searchWeatherByName(
          String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchWeatherByName,
          [name],
        ),
        returnValue: _i4.Future<List<_i5.WeatherSearchItemModel>>.value(
            <_i5.WeatherSearchItemModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.WeatherSearchItemModel>>.value(
                <_i5.WeatherSearchItemModel>[]),
      ) as _i4.Future<List<_i5.WeatherSearchItemModel>>);
}

/// A class which mocks [WeatherLocalDataSourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSourceInterface extends _i1.Mock
    implements _i6.WeatherLocalDataSourceInterface {
  @override
  _i4.Future<_i2.WeatherModel> getLastWeather() => (super.noSuchMethod(
        Invocation.method(
          #getLastWeather,
          [],
        ),
        returnValue: _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getLastWeather,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getLastWeather,
            [],
          ),
        )),
      ) as _i4.Future<_i2.WeatherModel>);

  @override
  _i4.Future<void> cacheLatestWeather(_i2.WeatherModel? weatherModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLatestWeather,
          [weatherModel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfoInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfoInterface extends _i1.Mock
    implements _i7.NetworkInfoInterface {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
